# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da99647f40eb5bff5a9e834480f2222e7d593544dd7ecfd239992eca8e0053ff1c81e71a9d959744caae7fa6ca2f6ab896518c752fbef9301bb02e524c37bd6d


production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_token: <%= ENV["SECRET_KEY_BASE"] %>
#production:
#  secret_key_base: da99647f40eb5bff5a9e834480f2222e7d593544dd7ecfd239992eca8e0053ff1c81e71a9d959744caae7fa6ca2f6ab896518c752fbef9301bb02e524c37bd6d
#  secret_token: da99647f40eb5bff5a9e834480f2222e7d593544dd7ecfd239992eca8e0053ff1c81e71a9d959744caae7fa6ca2f6ab896518c752fbef9301bb02e524c37bd6d


test:
  secret_key_base: 3ce3ca1a18ca1211b2073fd8f7ff1ae080b5ddaa7c45dcbb61e22ad2b6882635ebc030559f37369cf63fa46f0383ba09ac938e4800f27a8240b8a10849ef2237

# Do not keep production secrets in the repository,
# instead read values from the environment.
